base_url = "https://cherokeenewtestament.org"
compile_sass = true
highlight_code = true
build_search_index = true

taxonomies = [
    {name = "categories", paginate_by = 8, rss = true},
    {name = "tags", paginate_by = 8, rss = true},
    {name = "authors", paginate_by = 8, rss = true}
]

theme = "Zulma"

[extra]

zulma_title = "Cherokee New Testament"
zulma_brand = {text="Cherokee New Testament"}
zulma_theme = "superhero"
zulma_allow_theme_selection = true
